image: gitlab-registry.cern.ch/acts/machines/slc6:latest

stages:
    - build
    - test

variables:
    CMAKE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_DD4HEP_PLUGIN=on -DBUILD_MATERIAL_PLUGIN=on -DBUILD_TGEO_PLUGIN=on

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_lcg89_slc6.sh; set -e

check_format:
    stage: build
    # TODO remove once all files have been reformatted
    allow_failure: true
    tags:
        - cvmfs
    script:
        - CI/check_format .

check_license:
    stage: build
    # TODO remove once the license check is fixed
    allow_failure: true
    before_script: []
    script:
        - CI/check_license_local .

build_slc6_gcc:
    stage: build
    tags:
        - cvmfs
    script:
        - mkdir build_slc6_gcc
        - cd build_slc6_gcc
        - cmake ${CMAKE_ARGS} -DCMAKE_CXX_COMPILER=g++ ..
        - cmake --build .
    artifacts:
        paths:
            - build_slc6_gcc

build_slc6_clang:
    stage: build
    # TODO clang via cvmfs does not play with the required gcc includes
    allow_failure: true
    tags:
        - cvmfs
    script:
        - mkdir build_slc6_clang
        - cd build_slc6_clang
        - cmake ${CMAKE_ARGS} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="--gcc-toolchain=${GCC_TOOLCHAIN}" -DBoost_COMPILER=-gcc62 ..
        - cmake --build .

build_doc:
    stage: build
    tags:
        - cvmfs
    script:
        - mkdir build_doc
        - cd build_doc
        - cmake -GNinja -DBUILD_DOC=on -DBUILD_TESTS=off ..
        - cmake --build . -- doc
    artifacts:
        paths:
            - build_doc/doc/html

unit_tests:
    stage: test
    tags:
        - cvmfs
    script:
        - cmake --build build_slc6_gcc -- test
