image: gitlab-registry.cern.ch/acts/machines/slc6:latest

stages:
    - build
    - test
    - check

variables:
    CMAKE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_DD4HEP_PLUGIN=on -DBUILD_MATERIAL_PLUGIN=on -DBUILD_TGEO_PLUGIN=on
    DEFAULT_BUILDDIR: build_slc6_gcc

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_lcg89.sh; set -e

build_slc6_gcc:
    stage: build
    tags: [cvmfs]
    script:
        - mkdir build_slc6_gcc
        - cd build_slc6_gcc
        - CXX=g++ cmake ${CMAKE_ARGS} ..
        - cmake --build .
    artifacts:
        paths:
            - build_slc6_gcc

unit_tests_slc6_gcc:
    stage: test
    dependencies: [build_slc6_gcc]
    tags: [cvmfs]
    script:
        - cmake --build build_slc6_gcc -- test
    artifacts:
        paths:
            - build_slc6_gcc

build_slc6_llvm40:
    stage: build
    tags: [cvmfs]
    script:
        - source CI/setup_llvm40.sh
        - mkdir build_slc6_llvm40
        - cd build_slc6_llvm40
        - CXX=clang++ cmake ${CMAKE_ARGS} ..
        - cmake --build .
    artifacts:
        paths:
            - build_slc6_llvm40

unit_tests_slc6_llvm40:
    stage: test
    dependencies: [build_slc6_llvm40]
    tags: [cvmfs]
    script:
        - source CI/setup_llvm40.sh
        - cmake --build build_slc6_llvm40 -- test

build_cc7_gcc:
    stage: build
    image: gitlab-registry.cern.ch/acts/machines/cc7:latest
    tags: [cvmfs]
    script:
        - mkdir build_cc7_gcc
        - cd build_cc7_gcc
        - CXX=g++ cmake ${CMAKE_ARGS} ..
        - cmake --build .
    artifacts:
        paths:
            - build_cc7_gcc

unit_tests_cc7_gcc:
    stage: test
    dependencies: [build_cc7_gcc]
    image: gitlab-registry.cern.ch/acts/machines/cc7:latest
    tags: [cvmfs]
    script:
        - cmake --build build_cc7_gcc -- test

build_cc7_llvm40:
    stage: build
    image: gitlab-registry.cern.ch/acts/machines/cc7:latest
    tags: [cvmfs]
    script:
        - source CI/setup_llvm40.sh
        - mkdir build_cc7_llvm40
        - cd build_cc7_llvm40
        - CXX=clang++ cmake ${CMAKE_ARGS} ..
        - cmake --build .
    artifacts:
        paths:
            - build_cc7_llvm40

unit_tests_cc7_llvm40:
    stage: test
    dependencies: [build_cc7_llvm40]
    image: gitlab-registry.cern.ch/acts/machines/cc7:latest
    tags: [cvmfs]
    script:
        - source CI/setup_llvm40.sh
        - cmake --build build_cc7_llvm40 -- test

doc:
    stage: build
    tags: [cvmfs]
    script:
        - mkdir build
        - cd build
        - cmake -GNinja -DBUILD_DOC=on -DBUILD_TESTS=off ..
        - cmake --build . -- doc
    artifacts:
        paths:
            - build/doc/html

coverage:
    stage: check
    tags: [cvmfs]
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
    script:
        - cmake --build ${DEFAULT_BUILDDIR} -- coverage
    artifacts:
        paths:
            - ${DEFAULT_BUILDDIR}/coverage

format:
    stage: check
    # TODO remove once all files have been reformatted
    allow_failure: true
    tags: [cvmfs]
    script:
        - CI/check_format .

license:
    stage: check
    # TODO remove once the license check is fixed
    allow_failure: true
    before_script: []
    script:
        - CI/check_license_local .
