image: gitlab-registry.cern.ch/acts/a-common-tracking-sw/slc6:latest

stages:
    - build

variables:
    BUILD_TYPE: Release

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_slc6.sh; set -e

slc6-gcc:
    stage: build
    tags:
        - cvmfs
    script:
        - mkdir build_gcc
        - cd build_gcc
        - cmake -GNinja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DEIGEN_INCLUDE_DIR=${EIGEN_INCLUDE_DIR} ..
        - cmake --build .
    artifacts:
        paths:
            - build_gcc

slc6-clang:
    stage: build
    tags:
        - cvmfs
    script:
        - mkdir build_clang
        - cd build_clang
        - cmake -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBoost_COMPILER=-gcc62 -DEIGEN_INCLUDE_DIR=${EIGEN_INCLUDE_DIR} ..
        - cmake --build .
    artifacts:
        paths:
            - build_clang
