limits:
  "readability-inconsistent-declaration-parameter-name": 0
  "modernize-use-using": 0
  "readability-braces-around-statements": 0
  "modernize-use-override": 0
  "readability-implicit-bool-cast": 0

ignore:
  - cppcoreguidelines-pro-type-vararg
