name: Checks

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'develop/**'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: [self-hosted, linux]
    container: ghcr.io/acts-project/format14:v41
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: >
          git config --global safe.directory "$GITHUB_WORKSPACE"
          && CI/check_format .
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: changed
          path: changed
  format-py:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install black
        run: pip install black==22.3.0
      - name: Run black format check
        run: black --check . --extend-exclude ".*thirdparty.*"

  license:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check
        run: >
          sudo apt-get install -y git
          && CI/check_license.py . --exclude "*thirdparty/*"
  include_guards:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check
        run: >
          CI/check_include_guards.py . --fail-global --exclude "*thirdparty/*"
  pragma_once:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: >
          CI/check_pragma_once.sh
  end_of_line:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check
        run: >
          CI/check_end_of_file.py . --exclude "thirdparty/*" --reject-multiple-newlines --github
  boost_test_macro:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: >
          CI/check_boost_test_macro.sh
  smearing_config:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check
        run: >
          CI/check_smearing_config.py .
  cmake_options:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check
        run: >
          docs/parse_cmake_options.py CMakeLists.txt --write docs/getting_started.md --verify
  spelling:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install codespell
        run: >
          pip install codespell==2.2.5
      - name: Check
        run: >
          CI/check_spelling
  missing_includes:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Install clang
        run: >
          sudo apt-get install -y clang libeigen3-dev libboost-dev
      - name: Check
        run: >
          CI/missing_include_check.sh
  fpe_masks:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: >
          pip install -r CI/requirements_fpe_masks.txt
      - name: Check
        run: >
          CI/check_fpe_masks.py --token ${{ secrets.GITHUB_TOKEN }}
